### ISSUE TITLE
مشکل کانکت نشدن

### ISSUE THREAD

**Issue by mositurkish** [Musixal/Easy-Mesh#1]
کامکت نمیشه و با خطاهای زیر مواجه میشم 
حتی قبل این که کانفیگش کنم هم باز همین خطاها هست
اوبونتو 22 

Error: TonicTransportError(tonic::transport::Error(Transport, hyper::Error(Connect, ConnectError("tcp connect error", Os { code: 111, kind: ConnectionRefused, message: "Connection refused" }))))

easymesh.service - EasyMesh Network Service
     Loaded: loaded (/etc/systemd/system/easymesh.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Wed 2024-06-19 11:34:33 +0330; 1min 7s ago
    Process: 6073 ExecStart=/root/easytier/easytier-core -i 10.144.144.10 --peers udp://91.107.000.000:443 udp://91.107.000.000:443 udp://91.91.000.000.129:443 --hostname iran --network-secret 2a7e9f282da516210bba>   Main PID: 6073 (code=exited, status=1/FAILURE)
        CPU: 300ms

Jun 19 11:34:33 test01 systemd[1]: easymesh.service: Main process exited, code=exited, status=1/FAILURE
Jun 19 11:34:33 test01 systemd[1]: easymesh.service: Failed with result 'exit-code'.
Jun 19 11:34:33 test01 systemd[1]: easymesh.service: Scheduled restart job, restart counter is at 5.
Jun 19 11:34:33 test01 systemd[1]: Stopped EasyMesh Network Service.
Jun 19 11:34:33 test01 systemd[1]: easymesh.service: Start request repeated too quickly.
Jun 19 11:34:33 test01 systemd[1]: easymesh.service: Failed with result 'exit-code'.
Jun 19 11:34:33 test01 systemd[1]: Failed to start EasyMesh Network Service.
lines 1-14/14 (END)

**Comment by alisorena1993** [comment]
منم دقیقا یکی سرورهام همین مشکل رو داره و راه حلی براش پیدا نکردم

**Comment by shahram-noorani** [comment]
منم همین مشکل رو دارم

**Comment by worldsat** [comment]
منم همین مشکل رو دارم .کاش یه راه حلی براش پیدا بشه

**Comment by Musixal** [comment]
سلام. اشتباه کانفیگ کردید. از udp://91.107.000.000:443  مشخصه

**Comment by mositurkish** [comment]
> سلام. اشتباه کانفیگ کردید. از udp://91.107.000.000:443 مشخصه

سلام مجدد طبق آموزش کانفیگ کردم اوایل اوکی هست تا ترافیک زیاد میشه این اتفاق میوفته
