### ISSUE TITLE
دیسکانکت شدن سرور ایران حدودا هر 5 ساعت

### ISSUE THREAD

**Issue by MH-Zia** [Musixal/Easy-Mesh#2]
بعد از 2 روز استفاده از این اسکریپت، متوجه شدم هر 5 ساعت سرور ایران خود به خود از شبکه خارج میشه و برای حل این مشکل باید داخل سرور ایران Restart Service رو بزنم.
Watch Dogs هم فعال هست.
هر 60 ثانیه

به نظرم بهتره یه بخش اضافه بشه که Restart Service هر n ساعت انجام بشه.

**Comment by MH-Zia** [comment]
Update :
متاسفانه این مشکل هر 3 دقیقه اتفاق میوفته و دستی باید ریست کنم

**Comment by Musixal** [comment]
سلام. ممکنه روی یه سری دیتاسنترها استیبل نباشه. از تانل های دیگه استفاده کنید.
