### ISSUE TITLE
آیا ایزی مش قابلیت mux دارد؟

### ISSUE THREAD

**Issue by lostsoul6** [Musixal/Easy-Mesh#3]
درود وقت بخیر . آیا این اسکریپت mux دارد که تعداد کانکشن های رد و بدل شده بین سرور ایران و خارج رو بشه کمتر کرد یا نه . حجم بالای کانکشن بین سرور ایران و خارج باعث ایران اکسس شدن سرور میشه . تشکر

**Comment by Musixal** [comment]
سلام. خیر ندارد. خودتون با دکو و ماکس forward کنید

**Comment by lostsoul6** [comment]
من ایزی مش رو با ipv6 سرور ایران و خارج برقرار کردم . پینگ لوکال تانل اوکیه اما ترافیک با دکو هدایت نمیشه . با ha proxy منتقل میشه اما سرعت دانلود بسیار پایین هست . روی ipv6 خودتون تست کردید اوکی بوده ؟ حتی از بخش outbound هم به مقصد آی پی لوکال خارج ترافیک نمیره . به نظر مشکلی وجود داره .

**Comment by Musixal** [comment]
روی دکو اگر پنل سنایی هست تیک block private IPs باید برداشته باشه.
