### ISSUE TITLE
ترافیک دانلود بالا بروی سرور ایران

### ISSUE THREAD

**Issue by Dudukist** [Musixal/Easy-Mesh#7]
دوستان بنده چک کردم
دانلود بروی سرور ایران به شدت بالاست و هزینه رو چند برابر کرده؟
مشکل کجاست

**Comment by babakazizigithub** [comment]
کلا تانل هایی که بر پایه آی پی لوکال هستند دارای Overhead هستند - معمولا بین 10 تا 15 درصد مصرف بیشتر هست
به عنوان مثال اگر دیتاسنتری که ازش سرویس میگیرید هر ترابایت رو زده 500 تومن ,  شما با تانل های لوکال برای هر ترا بین 550 تا 575 باید پرداخت کنید

**Comment by Musixal** [comment]
اگر ارتباط P2P هست ترافیک نهایتا 20% زیاد میشه.
