### ISSUE TITLE
اتصال چند سرور ایران

### ISSUE THREAD

**Issue by JustPooya** [Musixal/Easy-Mesh#9]
سلام وقت بخیر
خسته نباشید و متشکرم بابت این اسکریپت بسیار کارامد
مشکلی که من دارم این هستش که طبق آموزش خودتون دو سرور ایران رو به یک خارج خواستم تانل کنم ، ارتباط شبکه برقرار میشه و ترافیک هم منتقل میشه اما در بخش روتینگ و پیر ها ، سرور دوم به صورت پوینت تو پوینت متصل نمیشه و نکست هاپ میخوره برای روتینگش
اینجوری ترافیک رو روی سرور اولیه ایران بالا میبره و عملا ترافیک بیش از حد میندازه بالاش
راه حلی نیست ؟
یک بار تست کردم پوینت تو پوینت شد اما بعد چند دقیقه قطع شد و مجدد رفت روی روتینگ نکست هاپ به سمت سرور ایران اول

**Comment by AntoniMatrix** [comment]
سلام وقت بخیر. سرور ایران یک رو به خارج تانل کنید و سرور ایران دو رو به سرور ایران یک. من دیشب این کار رو انجام دادم و مشکل نداشت. محدودیت های سرور ایرانتون هم بررسی کنید.

**Comment by JustPooya** [comment]
> سلام وقت بخیر. سرور ایران یک رو به خارج تانل کنید و سرور ایران دو رو به سرور ایران یک. من دیشب این کار رو انجام دادم و مشکل نداشت. محدودیت های سرور ایرانتون هم بررسی کنید.

درود ، ب همین صورت تانل میکنم اما بعد از برقراری اتصال ترافیک سرور ایران 2 ب جای اینکه p2p به خارج بره با ی روت بیشتر اول به ایران 1 و بعد به خارج میره
اما بعد از چند ساعت یا نهایتا یک روز این درست میشه و ترافیک p2p به خارج میره !
